version: "3.8"

services:
  frontend:
    build:
      context: ./order  # 这里是前端项目所在的目录
    ports:
      - "8080:80"
    networks:
      - app-network
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  # 挂载自定义的 Nginx 配置文件
    restart: always  # 确保容器在失败时重新启动

  backend:
    build:
      context: ./erp  # 后端项目目录
    environment:
      - DB_HOST=mysql  # 使用 MySQL 服务的名称而不是外部数据库的 IP
      - DB_PORT=3306
      - DB_USER=root  # 数据库用户
      - DB_PASSWORD=123456  # 数据库密码
      - DB_NAME=erp  # 数据库名称
    ports:
      - "5000:5000"
    networks:
      - app-network
    restart: always  # 确保容器在失败时重新启动

  mysql:
    image: mysql:8.0  # 使用官方 MySQL 镜像
    environment:
      MYSQL_ROOT_PASSWORD: 123456  # 设置 MySQL 根密码
      MYSQL_DATABASE: erp  # 创建数据库
    ports:
      - "3306:3306"  # 将 MySQL 端口映射到宿主机
    networks:
      - app-network
    volumes:
      - mysql_data:/var/lib/mysql  # 持久化数据

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
